const reducer = {
  LOADING: 'LOADING',
  REFRESH: 'REFRESH',
  ISLOGIN: 'ISLOGIN',
  FIRST_LAUNCH: 'FIRST_LAUNCH',
  DATA_LOGIN: 'DATA_LOGIN',
  DATA_MOVIES: 'DATA_MOVIES',
  DATA_MOVIES_SUCCESS: 'DATA_MOVIES_SUCCESS',
  DETAIL_MOVIE: 'DETAIL_MOVIE',
  DETAIL_MOVIE_SUCCESS: 'DETAIL_MOVIE_SUCCESS',
  DATA_FAVOURITES: 'DATA_FAVOURITES',
};

export default reducer;
